### ISSUE TITLE
‘./download_data.sh’ and './hic2txt.sh' could not be found

### ISSUE THREAD

**Issue by HappyLife-together** [kevinbdsouza/Hi-C-LSTM#1]
Can you provide ‘./download_data.sh’ and './hic2txt.sh'？Thank you

**Comment by mzc2113391** [comment]
same question, thank you

**Comment by kevinbdsouza** [comment]
Find the updated extract_chromsomes.sh in the data2 folder. You can run [extract_chromsomes.sh](https://github.com/kevinbdsouza/Hi-C-LSTM/blob/main/data2/extract_chromsomes.sh) to download the Hi-C data and extract chromosomes. You will have to download Juicer Tools first and specify the juicer_tools jar path in the sh file. Hope this helps.
